### ISSUE TITLE
Memory leaks in a127-magic

### ISSUE THREAD

**Issue by RafalJachimczyk** [apigee-127/magic#11]
Hi,

We have noticed our instances with a127 to be running out of memory while performing load tests. This is occuring when the a127 proxy reports errors to client. I have not done throughout testing for all possible scenarios of errors, so more investigations for memory leaks should be made.

Found memory leaks when:
- proxy errors when there is no api_key
- proxy errors when the api_key is invalid
- this is possibly happening on any error when error is returned in custom controller by : next(error) 

No memory leaks found in the below scenarios:
- api_key is valid

Suggesting that error messages are not cleaned up properly by V8 engine Garbage Collector.

Reproduction steps: 

This has been tested using latest a127-magic and latest volos modules. Our use case is more or less a passthrough proxy app (similar to https://github.com/apigee-127/a127-samples/tree/master/passthrough-proxy-with-keyvalidation)

```
$ git clone git@github.com:apigee-127/a127-samples.git
$ cd a127-samples/
$ npm install
$ cd passthrough-proxy-with-keyvalidation
$ npm install -g node-inspector
$ node-inspector
$ node --debug app.js
$ ab -c 20 -n 10000 http://localhost:10010/
$ ab -c 20 -n 10000 http://localhost:10010/api_key=VALID_API_KEY
```
Compare the results of memory heap allocation ie. the one without the valid key does not correctly garbage collect error messages.

Our investigation shows 29.5 MB of allocated memory after initial a127 startup, and 78.3MB after 10k connections made (When no api key is set or api key is invalid). The memory usage stays at this level until the app is restarted. There are no memory leaks when using correct API keys.

The problem persists when using vanilla https://github.com/apigee-127/a127-samples/tree/master/passthrough-proxy-with-keyvalidation and in our own custom controller.

![screen shot 2015-06-12 at 11 38 25](https://cloud.githubusercontent.com/assets/228999/8178404/abdb2508-1405-11e5-9c7f-e3cb66a98ecd.png)

Thanks,
Raf

**Comment by theganyo** [comment]
I've run tests with this on higher number of requests (eg. 100,000) and not found any memory leaks once the system has essentially reached a "steady state". The retained objects you see there, as far as I can tell, just haven't been collected yet. I did notice one bug in the sample, though, that perhaps is causing this to seem worse that it might otherwise be: It is allowing the error to be propagated through the connect middleware and to the console despite having been dealt with in the app.js. See this commit to the sample: https://github.com/apigee-127/a127-samples/commit/f8b3968e5cbc384c4867ef3c06a79a35110ac21f. If you carried this issue over into your app as well, it will be impacting your performance and creating extra garbage. Please let me know what you find.

**Comment by theganyo** [comment]
I'm closing this for now as I cannot recreate. If you have any more information, please let me know and reopen.
